### ISSUE TITLE
Typo in /pinout/1_wire

### ISSUE THREAD

**Issue by diegorodriguezv** [Gadgetoid/Pinout.xyz#130]
...following line to /boot/config.txt, **beofre**...

should be "before".

;)

**Comment by RogueM** [comment]
thanks, fixed! (will be live at next update)

**Comment by lurch** [comment]
Dunno if it's worth fixing, but it's still present in the 'translate' files for other languages
https://github.com/Gadgetoid/Pinout.xyz/search?utf8=%E2%9C%93&q=beofre&type=Code

**Comment by Gadgetoid** [comment]
Whoooooops! Yeah, worth fixing for posterity and sanity alone!

**Comment by RogueM** [comment]
yeah, those files need translating though :/
