### ISSUE TITLE
Rogue Desktop

### ISSUE THREAD

**Issue by lurch** [Gadgetoid/Pinout.xyz#147]
Looks like something might have gone wrong in https://github.com/Gadgetoid/Pinout.xyz/blob/master/src/fr/pin/pin-17.md ? ;-)

**Comment by RogueM** [comment]
interesting... those are normally symlink. I suspect they break when I'm using venv, or perhaps when I'm swapping machine. Or it could be the reason of a recent fr PR. I'll look into it.

**Comment by RogueM** [comment]
seems to have been spawned in a very early commit of the translation. Either way, fixed (I hope for good)

**Comment by lurch** [comment]
Looks like somehow the relative link had got converted to an absolute link. But all looks fine again now :+1:
