### ISSUE TITLE
Pin information for the PiTFT

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [Gadgetoid/Pinout.xyz#151]
As far as I know the PiTFT is probably the most well known display board besides the official screen, it would be nice to have it added to the list of boards.

Some useful information about the pin usage:

https://forums.adafruit.com/viewtopic.php?f=47&t=75974

**Comment by geek2003** [comment]
here is as much as I have managed to do can anyone add it to the site?

![tft](https://cloud.githubusercontent.com/assets/18628834/20038242/f2d42780-a427-11e6-825e-20a2251047c1.png)
[tft.txt](https://github.com/Gadgetoid/Pinout.xyz/files/573857/tft.txt)

**Comment by geek2003** [comment]
the main problem is there are so many versions of the pi TFT

**Comment by Gadgetoid** [comment]
If we name them followed by size and resolution it may help. Or we can simply be opinionated and list just one or two. I think most/all of them use the same pins for the display signal, though?

**Comment by RogueM** [comment]
I'm not sure if there are differences to the pinout... would need checking. There is no need for a custom kernel at this point though, so install instructions should be toned down to a sane level before pushing live ;-)

**Comment by RogueM** [comment]
the PiTFT+ 3.5 will be in the next update (commit https://github.com/Gadgetoid/Pinout.xyz/commit/ad33003efe65585be5d977428b5072011ecbc66c )

... will have to check whether others have the same pinout and could be merged into it, or ned their own overlay.

**Comment by BruceJohnJennerLawso** [comment]
Apologies for slow reply on this.

If we include nothing else, the 2.8 resistive & capacitive boards from adafruit as well as the 3.5 would be good to include. There are a multitude of knockoff tfts out there, but the adafruit ones are far away the most common.
