### ISSUE TITLE
Ground page

### ISSUE THREAD

**Issue by geek2003** [Gadgetoid/Pinout.xyz#152]
Just a little thing but on pinout.xyz/pinout/ground the ground pins along the left hand side are different and you can't see the text of ground. As I said it is a little thing but worth fixing!

**Comment by lurch** [comment]
I guess this must a side-effect of the changes made for #141

**Comment by Gadgetoid** [comment]
Yup, I believe I've broken this in my efforts to reign in the horrible nightmare hole of CSS I'd dug myself into. Should be an easy fix! Thanks for pointing it out.

**Comment by lurch** [comment]
Just spotted another small "problem", which is nicely illustrated by http://pinout.xyz/pinout/blinkt
The 'unused' Ground pins still have the black circle drawn around them (good), but the used ground pins don't have any circle around them, which makes them look weird.

**Comment by Gadgetoid** [comment]
I think this has also been fixed somewhere along the way, thanks. I have to squint to see the black circles :D
