### ISSUE TITLE
Graphical pinout missing SPI1 CE-pins

### ISSUE THREAD

**Issue by WereCatf** [Gadgetoid/Pinout.xyz#153]
The graphical pinout is real nice, but, as per the title, while it does show MISO, MOSI and SCLK for SPI1, it doesn't show the CE-pins for it. Minor oversight, but perhaps worth fixing.

**Comment by Gadgetoid** [comment]
The main view tries to capture some of the more common pin usages, so favours PWM over SPI1 CE0. For everything else- it's designed to be interactive, so you can usually find the information you need in a click or two. 

For example, you can still find full details of SPI pins here: http://pinout.xyz/pinout/spi

**Comment by RogueM** [comment]
still, BCM16 could be highlighted as a CE pin for SPI1?

**Comment by Gadgetoid** [comment]
True! I'll flag this up to do ;D

**Comment by Gadgetoid** [comment]
I never did get 'round to this, and looking back over it the fact SPI1 CE0 conflicts with the pin currently labelled as "PWM" makes me hesitant to bother with the SPI1 CE pins at all. Closing for the time being!
