### ISSUE TITLE
1-wire "More info" link wrong, and possible alternate pin settings?

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/Pinout.xyz#154]
The more info link for 1-wire links to DPI on the RaspberryPi.org website.

Also according to this thread https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=65137

It may be possible to set a custom pin for 1-wire, I haven't had time to read into it properly, but that may be information worth conveying.

**Comment by RogueM** [comment]
Yes, it's just a matter of passing the pin as parameter... it's documented in the dt overlay README in /boot/overlay

**Comment by RogueM** [comment]
link fixed and some info regarding choice of pin added.
