### ISSUE TITLE
wirinpi BCM0 and BCM1

### ISSUE THREAD

**Issue by robotrovsky** [Gadgetoid/Pinout.xyz#160]
Hi!

First i want to say, that i am using pinout.xyz very frequently and that it is a very nice tool!

In the wiringPi-overlay, there are missing the wiringPi Pins for BCM 0 and BCM 1. These are:

BCM0 = WriingPi Pin 30
BCM1 = WriingPi Pin 31

Please look at the translation in wiringPi.c Line 354:
https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L354

**Comment by Gadgetoid** [comment]
You're not wrong. These are "officially" don't-connect pins, but I don't see any harm in adding the WiringPi names for them.

Thanks for your feedback and support!

**Comment by RogueM** [comment]
interestingly those were documented under the physical pins. anyhow, added (will go live whenever next sync occurs).

**Comment by robotrovsky** [comment]
Thanks to you guys, for the nice tool!
