### ISSUE TITLE
Adafruit ultimate GPS hat complete file

### ISSUE THREAD

**Issue by geek2003** [Gadgetoid/Pinout.xyz#164]
here it is. I promised more adafruit boards.

[gps.txt](https://github.com/Gadgetoid/Pinout.xyz/files/629755/gps.txt)
![gps](https://cloud.githubusercontent.com/assets/18628834/20868638/121a9156-ba58-11e6-9083-757ec6841960.png)

not really an issue just don't know how to do pr's!

More on the way!

**Comment by geek2003** [comment]
![gps](https://cloud.githubusercontent.com/assets/18628834/20868653/a687ed20-ba58-11e6-9e02-4dcf83f14e93.png)
 sorry this is a better image

**Comment by geek2003** [comment]
Hello?

**Comment by RogueM** [comment]
Yes, thanks, noted... we'll review and publish it ASAP.

**Comment by geek2003** [comment]
Cheers! Looking to do one for the new adafruit audio phat/bonnet so expect it soon!

**Comment by RogueM** [comment]
done and ready to go.
