### ISSUE TITLE
Adafruit audio bonnet complete file 

### ISSUE THREAD

**Issue by geek2003** [Gadgetoid/Pinout.xyz#166]
yet again. It's me now back with the adafruit audio bonnet. I am very enthusiastic for the site and want to add to it. The audio.txt is the file

![audio](https://cloud.githubusercontent.com/assets/18628834/21020665/4b8f9da6-bd6d-11e6-80f6-53a8cd6f9ac3.png)

[audio.txt](https://github.com/Gadgetoid/Pinout.xyz/files/640163/audio.txt)

**Comment by Gadgetoid** [comment]
Thank you! Bear with us, the run up to Christmas is silly busy so we haven't had much chance to look into Pinout.

**Comment by RogueM** [comment]
done and ready to go.
