### ISSUE TITLE
Missing: "Raspberry Pi High-Precision AD/DA Expansion Board"

### ISSUE THREAD

**Issue by emmellsoft** [Gadgetoid/Pinout.xyz#167]
Hello pinout-people!   :-)
I didn't find this board on your https://pinout.xyz/boards page:

http://www.waveshare.com/High-Precision-AD-DA-Board.htm

**Comment by RogueM** [comment]
thanks for the request... there is enough info there so it should be possible to add.

If you are able to submit a draft overlay via PR though this will ensure it happens more rapidly as we don't often have time to assemble the needed info*.

* the average it takes me to make a board from scratch is about 30 mins, but someone more familiar with it may take significantly less without compromising accuracy - either way, time is the bottleneck at our end.

**Comment by RogueM** [comment]
actually the relevant link is this:
http://www.waveshare.com/wiki/High-Precision_AD/DA_Board

**Comment by Gadgetoid** [comment]
https://pinout.xyz/pinout/high_precision_adda_board
