### ISSUE TITLE
Adafruit Animated eyes bonnet

### ISSUE THREAD

**Issue by geek2003** [Gadgetoid/Pinout.xyz#174]
Here we go again but this time I am quick of the mark.
eyes.txt and eyes.png are the files.
![eyes](https://cloud.githubusercontent.com/assets/18628834/21901659/80e415f6-d8f0-11e6-8a61-c4d5e0d18e97.png)
[eyes.txt](https://github.com/Gadgetoid/Pinout.xyz/files/702470/eyes.txt)

**Comment by Gadgetoid** [comment]
Nice. Adafruit have definitely pushed the boat out with this one :D

**Comment by geek2003** [comment]
Currently working on some other Ada fruit hats!

**Comment by Gadgetoid** [comment]
Published as of https://github.com/Gadgetoid/Pinout.xyz/commit/7da4b8d0dbafa51306e098481fcd857552803158 - thank you!
