### ISSUE TITLE
Adafruit motor hat

### ISSUE THREAD

**Issue by geek2003** [Gadgetoid/Pinout.xyz#183]
Promised more and here I am again motor.txt and motor.png are the files

[motor.txt](https://github.com/Gadgetoid/Pinout.xyz/files/748612/motor.txt)
![motor](https://cloud.githubusercontent.com/assets/18628834/22562065/e9af7890-e972-11e6-98c2-2abc5b38a7ae.png)

**Comment by Gadgetoid** [comment]
c'mon! Make your changes on GitHub and submit them as PRs, you know you want to ;) It's a useful skill to have, and makes sure that your contributions are recorded.

Otherwise, thank you!

**Comment by geek2003** [comment]
Yeah sure I will give it a go for the matrix driver one I am working on at the moment!
