### ISSUE TITLE
Unicorn Hats require Ground at pin 9

### ISSUE THREAD

**Issue by Pyroseza** [Gadgetoid/Pinout.xyz#185]
Title says it all

**Comment by RogueM** [comment]
is this aquestion or an affirmation?

... but, yes, affirmative:
http://pinout.xyz/pinout/unicorn_hat

**Comment by Pyroseza** [comment]
An affirmation because I am trying to put jumpers between the hat and the pi so that I can use a motor hat alongside and couldn't figure out what was happening until I plugged the ground wire. Also read that all grounds are linked so it does not have to be at pin 9 bit can be any ground.

**Comment by RogueM** [comment]
hum, I'm pretty sure pin9 is a requirement. Some other may be connected but I don't think any other can be connected by themselves and the setup to work.

**Comment by Pyroseza** [comment]
Interesting, I'll test it and let you know. Do you think it's worth
mentioning on the pages as requirement? I think it would have been quit
handy to see it at a glance instead of googling for an hour.

**Comment by RogueM** [comment]
that is what the blob means... obviously all and any elctronic board requires vcc and ground. the pinout tell you all this info already, including which ground are electronically connected.

**Comment by Pyroseza** [comment]
Interesting I'll go read it now, I must've missed it. 

Can you recommend a decent place on the web to read about gpio pins on the raspi? 

I think I just confused myself earlier, also this is my first attempt with electronics. So I'm quite noob and have already burnt out 3 or so components for putting them in the wrong way.

Kind Regards,
Jarrod Price

--------

**Comment by RogueM** [comment]
I would recommend http://raspi.tv/rpi-gpio

**Comment by Pyroseza** [comment]
Thank you
