### ISSUE TITLE
Pins not connected on/since Pi B 2.0

### ISSUE THREAD

**Issue by BalzGuenat** [Gadgetoid/Pinout.xyz#196]
According to [this page](http://elinux.org/RPi_BCM2835_GPIOs#GPIO4) in the elinux wiki, several GPIO pins are not connected on the Pi B 2.0 and presumably also on the B 3.0. These pins are namely 12, 13, 19, 20, 21, 26 and more higher ones.

A corresponding notice should point this out where relevant, for example JTAG, where GPIO 26 cannot be used as TDI.

**Comment by RogueM** [comment]
I think you are confusing the Raspberry Pi 1 rev 2 with the Raspberry Pi 2... as marked at the top of that page, this document aim to document BCM2835 based-Pi, so it can't possibly be relevant to the Pi 2 and 3, which use the BCM2836 and BCM2837 respectively.

The Pi zero and Zero W use the BCM2835 but do have those pins connected, just like the RPi B+ metioned in that chart... in other words, that document is long outdated and is - for the most part - not relevant to Pis fitted with the J8 header (unless you solely check the 'RPi B+' column).

But, yes, pinout.xyz has no vocation to document early Pis, pre B+ (it used to be the case and it was highly confusing for newcomers).
