### ISSUE TITLE
CMIO3 pinouts

### ISSUE THREAD

**Issue by maurbeck** [Gadgetoid/Pinout.xyz#201]
Are there plans to have a CMIO3/CM3 pinout available here? Would be nice to have a graphical interface to all the pins and especially their alternate uses.

**Comment by lurch** [comment]
IMHO http://elinux.org/RPi_BCM2835_GPIOs is a better resource for that ;-)
I think the Raspberry Pi Compute Modules have too many pins to try and shoehorn into the pinout.xyz interface.

**Comment by maurbeck** [comment]
TYVM!

**Comment by maurbeck** [comment]
Is there a similar resource for a visual pinout description of ALL pins? This link describes the GPIO, but not where each pin 1-200 is physically located on the CM3 and its function.
