### ISSUE TITLE
Issue rendering website locally

### ISSUE THREAD

**Issue by radhikap18** [Gadgetoid/Pinout.xyz#225]
The README files mentions two steps in order to render the website locally. First, by using ./draft/publish and then opening the given link in the browser. 
However, for me, when I try the first step, I get an error saying:
-bash: ./draft/publish: No such file or directory
And then the link provided fails to open a valid page. Is there something I might be doing wrong?

**Comment by Gadgetoid** [comment]
The script is `draft/publish.sh`, and in order to run the site locally you should run `make LANG=en serve` - substituting your language of choice where appropriate.
