### ISSUE TITLE
Which connector does this refer to?

### ISSUE THREAD

**Issue by AndreKR** [Gadgetoid/Pinout.xyz#230]
Here's what I see:
![15020832214160](https://user-images.githubusercontent.com/1188538/29013126-2843fd82-7b41-11e7-8f4b-f3d865392f76.jpg)
There are 40 pins listed on pinout.xyz, which connector do they refer to?

**Comment by Gadgetoid** [comment]
Pinout predominately documents HATs and pHATs designed for the 40-pin GPIO header on the Pi B+ and upwards.

The 26-pin header on earlier Pi's (such as yours) is a subset of the 40-pin header, which includes all of the top 26 GPIO pins documented, but not BCM 0/1 and those after them.

Most HATs or pHATs that use just the first 26 pins  on the header can be used with your Pi, but you will need a 26-pin stacking header to make them fit.

**Comment by AndreKR** [comment]
Ah, thanks, very helpful. You could copy that straight to the website. :)
