### ISSUE TITLE
Show which boards likely won't play well together?

### ISSUE THREAD

**Issue by scruss** [Gadgetoid/Pinout.xyz#235]
Suggested enhancement that's currently only possible using `usespin.py` and some command-line nonsense: create a filter for boards that use the same pins and likely couldn't be piggybacked. For example, the Pimoroni [OnOff SHIM](https://pinout.xyz/pinout/onoff_shim) most likely won't work with the Pimoroni [Inky pHAT](https://pinout.xyz/pinout/inky_phat#) as they both use BCM 17.

**Comment by Gadgetoid** [comment]
This is a work in progress, as it happens: http://pi.gadgetoid.com/match/match.html

**Comment by Gadgetoid** [comment]
Continued: https://pinout.xyz/phatstack
