### ISSUE TITLE
Spelling Error on BCM15 (RXD)

### ISSUE THREAD

**Issue by MarkSetchell** [Gadgetoid/Pinout.xyz#254]
If you click on pin BCM15 (RXD) it pops up a window on the right where the word "receive" is misspelled as "recieve"

**Comment by Gadgetoid** [comment]
Oh wow! This must date back *years* to the original version of Pinout.... yup:

https://github.com/Gadgetoid/Pinout/blob/04937cda198bef62c3414503a176bfecef46ebab/pinout.html#L314-L318

D'oh! Very astute spot, I'll get it fixed.
