### ISSUE TITLE
Garatronic NadHAT board have disappear

### ISSUE THREAD

**Issue by garatronic** [Gadgetoid/Pinout.xyz#264]
Just a mistake ?
Can you correct it ?

**Comment by garatronic** [comment]
Not totally awaken, sorry.

**Comment by Gadgetoid** [comment]
Oh. Sorry. Were you linking to your "Manufacturer" page? I moved it into "Other" because there's only one, and the list of manufacturers was getting unwieldy.

**Comment by garatronic** [comment]
Understood. Time for me to develop few more boards ;-) 


De: "Philip Howard" <notifications@github.com> 
À: "Gadgetoid" <Pinout.xyz@noreply.github.com> 
Cc: "Garatronic" <github@garatronic.fr>, "State change" <state_change@noreply.github.com> 
Envoyé: Mardi 13 Mars 2018 10:39:49 
Objet: Re: [Gadgetoid/Pinout.xyz] Garatronic NadHAT board have disappear (#264) 



Oh. Sorry. Were you linking to your "Manufacturer" page? I moved it into "Other" because there's only one, and the list of manufacturers was getting unwieldy.
