### ISSUE TITLE
Wrong Pin Information for the raspiaudio audio+ hat

### ISSUE THREAD

**Issue by Codedotexe** [Gadgetoid/Pinout.xyz#296]
The audio+ hat from raspiaudio needs the 3.3V pin NOT the 5V pin, otherwise it will not work. The other pin information for the hat is correct.
Source: https://www.raspiaudio.com/home

**Comment by Gadgetoid** [comment]
Looks like you're correct. I wonder if they've changed or if it's always been wrong!

**Comment by Gadgetoid** [comment]
Thanks for pointing it out- should be fixed when I next republish.
