### ISSUE TITLE
Wrong 5v Power pin information for Blinkt!

### ISSUE THREAD

**Issue by herbsoft** [Gadgetoid/Pinout.xyz#298]
For the Blinkt! that I have, I have noted that it uses the 5v Power from Pin 2 and not from Pin 4 as is currently illustrated.

**Comment by Gadgetoid** [comment]
You've got a first run Blinkt!

We actually changed from using pin 2 to pin 4 to break the rotational symmetry of the header- IE: to prevent it being possible to fit backwards connecting 5v to GND and GND to 5v.

I might add a note to the Blinkt! file to mention this, actually. Thanks.
