### ISSUE TITLE
Outdated reference to wiringpi python library

### ISSUE THREAD

**Issue by mcaden** [Gadgetoid/Pinout.xyz#302]
The page says to use `wiringpi2` but if you go to its [listing on pypi](https://pypi.org/project/wiringpi2/) it says:

> This package has been deprecated in favour of using the name “WiringPi” which provides the same exact functionality.

So the page should be updated.

**Comment by lurch** [comment]
Yup, see also https://github.com/WiringPi/WiringPi-Python/issues/27

**Comment by Gadgetoid** [comment]
Good spot. I should probably fix that!

**Comment by Gadgetoid** [comment]
Thank you- should be fixed in the next republish!
