### ISSUE TITLE
Layout oddness on main board page

### ISSUE THREAD

**Issue by tuftii** [Gadgetoid/Pinout.xyz#317]
On the live site at the moment there seems to be a 3 board gap between the Cirrus Logic Audio Card and the cube:bit Base board.

![alignment_odd](https://user-images.githubusercontent.com/3215045/58788053-ff124000-85e2-11e9-9516-7eb8804ea3cf.png)

([see here](https://pinout.xyz/boards#))

I'm using Firefox 67.0 with ad-block disabled and no other add ons.

Not sure if this is important or not, or how to solve it, but couldn't see an open issue so here we are :smile:

**Comment by lurch** [comment]
I'm seeing the same thing (also with the same version of FF).

**Comment by tuftii** [comment]
Oddly, it's not a problem in Chrome. :woman_shrugging: 

![chome-not-odd](https://user-images.githubusercontent.com/3215045/58818982-17a44980-8627-11e9-94b3-661f074057a3.png)

**Comment by Gadgetoid** [comment]
Weirdly I don't see this on Firefox! It'll be the text busting out of the bottom of the layout and causing the elements underneath to wrap. There's probably a much more modern way to lay out a grid of elements like this that I should be looking into.

I think the boards page needs some TLC anyway because I *hate* the dependency on Javascript. I've taken pains to make sure there's as little JS and other overhead in this site as possible- Google Analytics notwithstanding for my own vanity.

Giving each manufacturer, form-factor and type its own HTML page would be a nice start perhaps? Ideas welcome!

**Comment by lurch** [comment]
> It'll be the text busting out of the bottom of the layout

Oh yeah - in @tuftii 's FF screenshot the text under the Cellular IOT HAT has split over 3 lines, whereas in the Chrome screenshot it's only wrapped onto two lines.

:+1: for reduction of the amount of JS! IMHO the "proper" solution would be to move the current JS filtering logic to the server-side (using something like PHP), but it's up to @Gadgetoid to come up with a solution that meets his available development time and his server's capabilities :slightly_smiling_face:

**Comment by tuftii** [comment]
I mean... the simple solution is to just shorten the name as that is *quite* the name for a HAT. Limit to two lines (whatever characters fit roughly?).

**Comment by lurch** [comment]
Yeah, editing the name down to just "Cellular IoT Application HAT" probably makes sense. I had a click through to the Sixfab site, and they have a [Cellular IoT HAT](https://sixfab.com/product/raspberry-pi-lte-m-nb-iot-egprs-cellular-hat/) and a [Cellular IoT Application HAT](https://sixfab.com/product/raspberry-pi-cellular-iot-application-hat/) so there's probably no need for the "LTE-M & NB-IoT & eGPRS" suffix? ping @saucompeng

**Comment by lurch** [comment]
It's a good thing the JamHAT isn't named the "ModMyPi Buttons and LEDs and Buzzer addon board for Raspberry Jams" :rofl:

**Comment by tuftii** [comment]
> 
> 
> It's a good thing the JamHAT isn't named the "ModMyPi Buttons and LEDs and Buzzer addon board for Raspberry Jams" rofl

100% can be arranged, I'm building a PR ASAP... :rofl:

**Comment by saucompeng** [comment]
> Yeah, editing the name down to just "Cellular IoT Application HAT" probably makes sense. I had a click through to the Sixfab site, and they have a [Cellular IoT HAT](https://sixfab.com/product/raspberry-pi-lte-m-nb-iot-egprs-cellular-hat/) and a [Cellular IoT Application HAT](https://sixfab.com/product/raspberry-pi-cellular-iot-application-hat/) so there's probably no need for the "LTE-M & NB-IoT & eGPRS" suffix? ping @saucompeng

@lurch  Yes, you are right. Could you fix it?

**Comment by lurch** [comment]
> @lurch Yes, you are right. Could you fix it?

I can't, but @Gadgetoid can :wink:

**Comment by tuftii** [comment]
I've shortened the text so this formatting issue never happens, but I can now see PR #333 fixes it properly! :+1:
