### ISSUE TITLE
Non-translated "localised" boards pages are missing

### ISSUE THREAD

**Issue by lurch** [Gadgetoid/Pinout.xyz#319]
Previously, if a translation of a board page was missing, you just used the English version, e.g. https://de.pinout.xyz/pinout/1_wire_pi_plus#
But it seems there are now some missing pages, e.g. https://de.pinout.xyz/pinout/jamhat#

Which means that https://de.pinout.xyz/boards# has many fewer boards listed than https://pinout.xyz/boards# and for some reason the DE boards page has an empty blue square in the "Type" list on the left :confused:

**Comment by Gadgetoid** [comment]
I haven't regenerated the non-UK sites for a little while- mostly out of subtle paranoia. If I break something, I don't want to break everything at once. 

I need to bite the bullet and hit the "Make website" button.

**Comment by Gadgetoid** [comment]
Oh boy this is a can of worms I've just opened!

**Comment by tuftii** [comment]
Ah. I was about to open an issue noting that some pages seem to be in German today, but I'm assuming this is related?

https://pinout.xyz/pinout/scorezero# for example... :de:

**Comment by Gadgetoid** [comment]
In my infinite wisdom I had a Makefile which took a LANG and a TARGET parameter and in almost all cases these should both be the same, but they both default to `en`.

I then did a `make LANG=de` and you can guess the rest 🤦‍♂

**Comment by tuftii** [comment]
Genau! :laughing:

**Comment by Gadgetoid** [comment]
This reminded me to republish everything :D
