### ISSUE TITLE
Why the first 3.3v pin (physical pin 1) representation is the only one with square shape?

### ISSUE THREAD

**Issue by carlosbfeitozafilho** [Gadgetoid/Pinout.xyz#342]
My OCD is driving me crazy because of this...

Well, just joking, but there are a reason why this is the only one pin with square shape representation?

**Comment by Gadgetoid** [comment]
It's the pin 1 designator. I appreciate there are also numbers, but using a square for pin 1 is... somewhat... canonical for header pinouts.

**Comment by lurch** [comment]
If you look at the underside of the GPIO header on an actual RPi, you'll see that Pin1 has a square solder-pad too, whilst all the others are round.
See e.g. the second image on this page https://www.raspberrypi.org/products/raspberry-pi-zero/

**Comment by lurch** [comment]
See also #267

**Comment by carlosbfeitozafilho** [comment]
Thank you guys!
Now I understand :)

**Comment by lurch** [comment]
> Now I understand :)

Can this issue be closed then? :)
