### ISSUE TITLE
Missing CSS in the public resources

### ISSUE THREAD

**Issue by peterblazejewicz** [Gadgetoid/Pinout.xyz#345]
It seems the public page is missing changes required for links in the legend:
https://github.com/Gadgetoid/Pinout.xyz/pull/334
This makes the links looks so '90s:
![image](https://user-images.githubusercontent.com/14539/66607482-99e3e200-ebb4-11e9-9448-07c4d4065500.png)
Maybe I've missed something in the PR?

Thanks!

**Comment by Gadgetoid** [comment]
Nope this is entirely my fault during the rebuild process! Good spot. I'd wondered why the links looked 90s but ultimately decided I didn't care 😆

**Comment by Gadgetoid** [comment]
Fixed! https://pinout.xyz/
