### ISSUE TITLE
Set CSS background and color to default

### ISSUE THREAD

**Issue by Zocker1999NET** [Gadgetoid/Pinout.xyz#354]
The page does not configure the `background` and `color` properties to default first, it instead expects that the user has not modified his default values for background and text color. Cause I changed these values so websites without an unique proper style will be adapted to the style of my desktop, see:
![image](https://user-images.githubusercontent.com/1645646/73261798-b8ea9c00-41c4-11ea-8e5f-780881823946.png)
However the style of this page is too customized to can be adaptive to the user configuration, so I would propose to define these properties.

I would propose this change by myself, however I do not know to which file I should add these properties cause there are three style sheet files in the `resources` directory: `pinout.css`, `pinout.scss` and `pinout.scss.css`.

**Comment by Gadgetoid** [comment]
Hopefully this is now fixed! Or at least mostly fixed.

**Comment by Zocker1999NET** [comment]
Is fixed, thanks @Gadgetoid
