### ISSUE TITLE
Pirate Audio 3W pinout error

### ISSUE THREAD

**Issue by scopeseducation** [Gadgetoid/Pinout.xyz#358]
Hi!
I found that for the 'Pirate Audio: 3W Stereo Amp' BCM8 is not used but BCM7.
Thanks for maintaining a great site!
Florian

**Comment by MisterEmm** [comment]
Thanks Florian you've saved me a lot of trial & error! Wired mine up with jumpers according to the pinout, audio was working but no image, added a cable to BCM7 and now fully working (Speaker version).

**Comment by Gadgetoid** [comment]
Ooof. Thank you for pointing this out. This looks to be true of *all* the Pirate Audio boards. I'll try to get this fixed ASAP.
