### ISSUE TITLE
RaspiAudio Mic+ also needs GPIO 20 / pin 38 for the microphone

### ISSUE THREAD

**Issue by HorstBaerbel** [Gadgetoid/Pinout.xyz#359]
See [here](https://www.raspiaudio.com/raspiaudio-aiy). This is missing in [https://pinout.xyz/pinout/raspiaudio_audio_speakers_mic#](https://pinout.xyz/pinout/raspiaudio_audio_speakers_mic#).
Also it will use GPIO 16 / pin 36 if you use the Google AIY driver.

**Comment by lurch** [comment]
@roscop13 added this board initially (in #270 ), so giving him a quick ping in case he has any comments :slightly_smiling_face:

**Comment by Gadgetoid** [comment]
Amazing, the linked resource uses a screencap with amendments instead of raising a PR 😆 

I think I should probably fix this!

**Comment by Gadgetoid** [comment]
Should be fixed, pending flushing through the CloudFlare cache- https://pinout.xyz/pinout/raspiaudio_audio_speakers_mic?v=1
