### ISSUE TITLE
There's a tab for ground pins, but not for 3v3 or 5v

### ISSUE THREAD

**Issue by 2231puppy** [Gadgetoid/Pinout.xyz#360]

**Comment by lurch** [comment]
Duplicate of #314 ?

**Comment by 2231puppy** [comment]
I guess it is. Sorry, didn't see that. I should have looked a bit deeper into the history.

**Comment by Gadgetoid** [comment]
No worries, I'll close this in favour of the other. I'm long overdue a sprint on Pinout to sort out all sorts of quirks and bugs so hopefully I'll get this done in July.
