### ISSUE TITLE
Add Raspberry Pi 1 pinout

### ISSUE THREAD

**Issue by merwok** [Gadgetoid/Pinout.xyz#363]
Hello!  People are still using first generation raspberry pis, so it would be great if the site would allow selecting the 26-pin version of the headers.  Cheers!

**Comment by lurch** [comment]
Duplicate of #346 ?

**Comment by merwok** [comment]
Ah I didn’t find that ticket when searching!  It wasn’t clear (from reading various pages about gpio-shutdown overlay) that the old pinout was a subset of the new one, so I didn’t understand why pinoutxyz didn’t show more than one pi model.  Thanks for replying!
