### ISSUE TITLE
When selecting 5v, only one of the pins is selected.

### ISSUE THREAD

**Issue by BERENGENITA** [Gadgetoid/Pinout.xyz#370]
I have noticed that, if you click on 5v, at the bottom of the page, only one of the two 5v pins is highlighted. I attach a small video.

https://i.gyazo.com/91679e0907525a16e81ba56930cda63d.mp4

I am aware that this is minor, but if someone could fix it, it would be great.

**Comment by lurch** [comment]
Duplicate of #314 ?
