### ISSUE TITLE
Blinkt! Amend with note for early versions

### ISSUE THREAD

**Issue by nickwebcouk** [Gadgetoid/Pinout.xyz#378]
Regarding - Can a note be added to say that early versions of Blinkt! ran power for 5V via Pin 2, and not Pin 4. 

See

https://twitter.com/nickwebcouk/status/1305838819816673280?s=20

Thanks,

Nick

**Comment by Gadgetoid** [comment]
Yes, yes I can. Sorry for sending you on a wild goose chase.

**Comment by nickwebcouk** [comment]
Absolutely no goose chase at all! I appreciate this will probably be quite rare but if it saves some head scratching for someone in the future!

**Comment by Gadgetoid** [comment]
Oh it looks like there was already a message, but it's virtually impossible to see unless you're looking for it. Trying to refactor the page to be clearer:

![image](https://user-images.githubusercontent.com/1746967/93232671-117da200-f772-11ea-97a3-04e483f56b53.png)

**Comment by nickwebcouk** [comment]
Well thats embarrassing. I read that page a good few times and never even noticed. Sorry for the extra work!

**Comment by Gadgetoid** [comment]
It's okay, I only saw it because I was *looking* for it (and wrote it, probably). If this results in better clarity for other users, it's time well spent!
