### ISSUE TITLE
Voltage after shutdown

### ISSUE THREAD

**Issue by rulet** [Gadgetoid/Pinout.xyz#397]
Does 2 and 4 pins(as on this scheme https://pinout.xyz/#) always keep 5v after complete shutdown?
I just want to connect IR receiver to it to turn on pi remotely.

**Comment by lurch** [comment]
I think it might vary by model of Pi - I believe that for models prior to the Pi 4B those pins did stay powered; I'm not sure what the Pi 4B does; I recall reading in a forum thread that the Pi 400 _does_ cut power to the GPIO header when it's in the shutdown state.
