### ISSUE TITLE
GPIO 19 is not included in `PWM` selection

### ISSUE THREAD

**Issue by MitterdorferMathias** [Gadgetoid/Pinout.xyz#398]
GPIO 19 has `ALT5=PWM1`

**Comment by felixkasza** [comment]
+1.

As for contributing the change myself (and changing "uses 3 pins" for the "PWM" text and so on), I am too stupid to understand how the site is built. For instance, the missing pin-33.md file in src/en/pin/ clearly causes a very useful tabel to appear, Why is that very useful table not there when there is a pin-NN.md file? Too bad.

I'll stick with crypto and file systems. :)
