### ISSUE TITLE
"Alternative" Pi-Pinouts

### ISSUE THREAD

**Issue by red-scorp** [Gadgetoid/Pinout.xyz#405]
There are different "alternative" Pis with compatible 40-pin connector available:
- banana Pi & Co
- Orange Pi & Co
- ASUS Tinker & Co

Will you add any information on them in your website?
- differences in pin-out
- compatibility with HATs
- differences in initialization of pins

**Comment by Gadgetoid** [comment]
I don't use any of the above and can't really speak in any way authoritatively about them. Additionally none of the manufacturers of these boards have ever so much as given me the time of day, nor shown any interest in a pinout.xyz for their products. So generally no- Raspberry Pi or bust :laughing:
