### ISSUE TITLE
RAM value incorrect

### ISSUE THREAD

**Issue by FloridaBill-Villages** [Gadgetoid/Pinout.xyz#409]
I have a new Pi 4 with 8GB RAM. 
When I run "pinout":
The board is reported as "Pi Model 4B V1.4". 
The RAM is reported as "NoneMb".

**Comment by Gadgetoid** [comment]
I think your issue is with:  https://github.com/gpiozero/gpiozero

**Comment by lurch** [comment]
I think this is fixed in the latest version of GpioZero? ping @bennuttall

**Comment by bennuttall** [comment]
Yes - fixed in 1.6 - update with pip or wait a few days for it to appear in apt
