### ISSUE TITLE
Add Pimoronni Audio Amp SHIM and Audio DAC SHIM

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/Pinout.xyz#415]
The two Pimoronnis
![image](https://user-images.githubusercontent.com/1746967/117968674-5a482380-b31e-11eb-88c2-23d2e9b71ae6.png)

**Comment by lurch** [comment]
Which one is the PIrate and which one is the NInja?

**Comment by Gadgetoid** [comment]
I don't know, but I had totally forgotten this, opened this issue and gave myself a laugh. 😆 

We should prop up a local bar sometime, do our bit for the economy, y'know?

**Comment by lurch** [comment]
Fo shure! Lemme know the next time you're down this way :beer:  (although we might only be allowed to prop up a table, rather than propping up the bar!)

**Comment by Gadgetoid** [comment]
I live down this way now 😆

**Comment by lurch** [comment]
![image](https://user-images.githubusercontent.com/476186/119049882-ffb36500-b9b8-11eb-940a-2935c4e30ae1.png)

**Comment by Gadgetoid** [comment]
Well that's just a bare-faced lie! I should probably update it 😆  *updates quickly*

**Comment by lurch** [comment]
![image](https://user-images.githubusercontent.com/476186/119050354-a4ce3d80-b9b9-11eb-8da6-0c31717dccc3.png)

![image](https://user-images.githubusercontent.com/476186/119050404-b7487700-b9b9-11eb-913e-42e1fb05dc31.png)


Snap! :grinning:

**Comment by Gadgetoid** [comment]
Although it's a bloody stretch to call here "Cambridge"! 👀  It's close enough.
