### ISSUE TITLE
"RAM: NoneMb" reported for 8GB rpi4

### ISSUE THREAD

**Issue by Kalixberen** [Gadgetoid/Pinout.xyz#417]
Hi ! 
thanks for a great program.
pinout is very helpful indeed.
but- maybe a minor question - pinout reported "RAM: NoneMb" for my 8GB rpi. 
Tried to find out if you already know this but did not find any in this way.

**Comment by lurch** [comment]
See #379 and #409 :wink:

**Comment by Kalixberen** [comment]
Thanks lurch!
Yea,  just notis that there was some closed issues that adressed the topic.
