### ISSUE TITLE
Can you add interstate75

### ISSUE THREAD

**Issue by PaulskPt** [Gadgetoid/Pinout.xyz#440]
Please add the interstate75
Tnx!

**Comment by lurch** [comment]
Huh? https://shop.pimoroni.com/products/interstate-75 doesn't have a Raspberry Pi HAT connector? Whereas https://pinout.xyz/boards all do.

**Comment by PaulskPt** [comment]
You're totally right. Sorry for the stupid question.

**Comment by Gadgetoid** [comment]
... perhaps :eyes: 

https://pico.pinout.xyz/
