### ISSUE TITLE
max current

### ISSUE THREAD

**Issue by Bra1nsen** [Gadgetoid/Pinout.xyz#443]
Hey all,

I would like to set up a pid controlled heating wire via my raspi. but i wanted to get advice from experienced experts first - i hope i'm in the right place here.

i wanted to control a mosfet via pwm and regulate a 1 meter heating wire to 80°c. does that work with the available 5v or are there problems with the current?

**Comment by lurch** [comment]
For any high-current applications, it's probably worth driving the load directly from a separate supply, like is done with motors?
https://projects.raspberrypi.org/en/projects/physical-computing/14

**Comment by Bra1nsen** [comment]
okay and the battery gets charged/managed by the raspy?

**Comment by lurch** [comment]
I think https://forums.raspberrypi.com/ might be what you're looking for? :wink:  Lots of helpful people there.
